import { Request, Response, NextFunction } from "express";
import { AppError } from "../utils/app-error";

type HttpError = Error & {
  status?: number;
  statusCode?: number;
};

export const globalErrorHandler = (
  err: HttpError,
  _req: Request,
  res: Response,
  _next: NextFunction,
): void => {
  // Errors intentionally thrown by our application
  if (err instanceof AppError) {
    res.status(err.statusCode).json({
      success: false,
      message: err.message,
    });

    return;
  }

  // Errors generated by Express/middleware
  // Example: express.json() failing to parse malformed JSON
  const statusCode = err.statusCode ?? err.status;

  if (statusCode && statusCode >= 400 && statusCode < 500) {
    res.status(statusCode).json({
      success: false,
      message: "Invalid request",
    });

    return;
  }

  // Unexpected server errors
  console.error(err);

  res.status(500).json({
    success: false,
    message: "Internal server error",
  });
};
